### ISSUE TITLE
bcl2fastq can´t be downloaded

### ISSUE THREAD

**Issue by fwa93** [arteria-project/arteria-packs#96]
Hello,
The installation fails because you need to need to log in to illumina to download bcl2fastq.
Below is the output + error message when I tried to install without changing anything.

On a side note:  I succesfully downloaded manually bcl2fastq and got it into the docker environment. There are however some dependency issues regarding "pathlib", "requests", and "six" that need to be fixed if/when you have fixed the illumina stuff. At least I got problems with those.  But as I said before the output below is from when I changed absolutely nothing

```
# I have these installed
# docker-compose version 1.29.2  (installed in conda environment)
# GNU Make 4.3
# Docker 20.10.18


# clone repo		
git clone https://github.com/arteria-project/arteria-packs.git

# make up
(arteria) [root@rosalind arteria-packs]# make up
mkdir -p -m 2770 docker-mountpoints/bcl2fastq-output
mkdir -p -m 2770 docker-mountpoints/monitored-folder
mkdir -p -m 2770 docker-runtime/entrypoint.d
mkdir -p -m 2770 docker-runtime/st2.d
docker volume create --opt "device=/aux/db/workdir_fwa010/arteria2/arteria-packs/docker-mountpoints/monitored-folder/" --opt "type=local" --opt "o=bind" monitored-dir-volume
monitored-dir-volume
docker-compose up -d
Creating network "arteria-packs_private" with driver "bridge"
Creating network "arteria-packs_public" with driver "bridge"
Creating volume "arteria-packs_mongo-volume" with default driver
Creating volume "arteria-packs_postgres-volume" with default driver
Creating volume "arteria-packs_rabbitmq-volume" with default driver
Creating volume "arteria-packs_redis-volume" with default driver
Creating volume "arteria-packs_stackstorm-log-volume" with default driver
Creating volume "arteria-packs_monitored-dir-volume" with default driver
Building runfolder-service
Sending build context to Docker daemon  3.072kB
Step 1/8 : FROM python:2.7
2.7: Pulling from library/python
7e2b2a5af8f6: Already exists
09b6f03ffac4: Already exists
dc3f0c679f0f: Already exists
fd4b47407fc3: Already exists
b32f6bf7d96d: Already exists
6f4489a7e4cf: Already exists
af4b99ad9ef0: Already exists
39db0bc48c26: Already exists
acb4a89489fc: Already exists
Digest: sha256:cfa62318c459b1fde9e0841c619906d15ada5910d625176e24bf692cf8a2601d
Status: Downloaded newer image for python:2.7
 ---> 68e7be49c28c
Step 2/8 : RUN apt-get update
 ---> Running in 2090f5dd19b1
Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [380 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
Fetched 8511 kB in 1s (5773 kB/s)
Reading package lists...
Removing intermediate container 2090f5dd19b1
 ---> 736fc73ecfd1
Step 3/8 : RUN git clone https://github.com/arteria-project/arteria-runfolder.git
 ---> Running in cf8e54b59469
Cloning into 'arteria-runfolder'...
Removing intermediate container cf8e54b59469
 ---> a568b69d7be5
Step 4/8 : WORKDIR arteria-runfolder
 ---> Running in c881e8a15ce6
Removing intermediate container c881e8a15ce6
 ---> 447059b2e0b5
Step 5/8 : COPY app.config config/
 ---> e678028c1db1
Step 6/8 : RUN pip install -r requirements/dev .
 ---> Running in d6db8f4ada21
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Processing /arteria-runfolder
Collecting arteria==1.1.2
  Downloading arteria-1.1.2-py2.py3-none-any.whl (10 kB)
Collecting jsonpickle==0.9.2
  Downloading jsonpickle-0.9.2.tar.gz (59 kB)
Collecting tornado==4.2.1
  Downloading tornado-4.2.1.tar.gz (434 kB)
Collecting PyYAML==3.13
  Downloading PyYAML-3.13.tar.gz (270 kB)
Collecting xmltodict==0.11.0
  Downloading xmltodict-0.11.0-py2.py3-none-any.whl (7.2 kB)
Collecting nose==1.3.7
  Downloading nose-1.3.7-py2-none-any.whl (154 kB)
Collecting nose-watch==0.9.1
  Downloading nose-watch-0.9.1.tar.gz (3.6 kB)
Collecting requests==2.20.0
  Downloading requests-2.20.0-py2.py3-none-any.whl (60 kB)
Collecting mock==1.3.0
  Downloading mock-1.3.0-py2.py3-none-any.whl (56 kB)
Collecting backports.ssl_match_hostname
  Downloading backports.ssl_match_hostname-3.7.0.1.tar.gz (5.7 kB)
Collecting certifi
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Collecting watchdog>=0.6
  Downloading watchdog-0.10.7.tar.gz (102 kB)
Collecting idna<2.8,>=2.5
  Downloading idna-2.7-py2.py3-none-any.whl (58 kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
Collecting pbr>=0.11
  Downloading pbr-5.11.0-py2.py3-none-any.whl (112 kB)
Collecting funcsigs; python_version < "3.3"
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl (17 kB)
Requirement already satisfied: six>=1.7 in /usr/local/lib/python2.7/site-packages (from mock==1.3.0->-r requirements/dev (line 5)) (1.14.0)
Collecting pathtools>=0.1.1
  Downloading pathtools-0.1.2.tar.gz (11 kB)
Building wheels for collected packages: jsonpickle, tornado, PyYAML, nose-watch, runfolder, backports.ssl-match-hostname, watchdog, pathtools
  Building wheel for jsonpickle (setup.py): started
  Building wheel for jsonpickle (setup.py): finished with status 'done'
  Created wheel for jsonpickle: filename=jsonpickle-0.9.2-py2-none-any.whl size=25856 sha256=d3b28baaf8e6cb0317cfae0805206467291808968a70c8b7e82eb1dfd22d755f
  Stored in directory: /root/.cache/pip/wheels/ad/a6/99/44e3991e59eb009c1fb1bab5c96bc817e056c7de02f23513af
  Building wheel for tornado (setup.py): started
  Building wheel for tornado (setup.py): finished with status 'done'
  Created wheel for tornado: filename=tornado-4.2.1-cp27-cp27mu-linux_x86_64.whl size=385706 sha256=9fe3ffed3706c2a03c00906a92afb05ca8e6f4d2eebfcf1dbbde34afe6d0d611
  Stored in directory: /root/.cache/pip/wheels/45/d4/0d/f8a0bcad46d9f3a3f4264cd1a0024d87cbe481c91f0c0317bf
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-3.13-cp27-cp27mu-linux_x86_64.whl size=401217 sha256=9253d9f81c6738048452e44d54364f83895e04de66e1728a7b8c3832386f82d1
  Stored in directory: /root/.cache/pip/wheels/1e/05/0e/1b73fc4c2cc86f02c3e7b75d1c14bd796dd2be8ab252b34dab
  Building wheel for nose-watch (setup.py): started
  Building wheel for nose-watch (setup.py): finished with status 'done'
  Created wheel for nose-watch: filename=nose_watch-0.9.1-py2-none-any.whl size=4653 sha256=f8da1b53209e1933abe09589429be58972de0375cdfd0ddc5da11258c2b62486
  Stored in directory: /root/.cache/pip/wheels/65/d4/d9/f7f1fcb743181ffb59209550c79e61067eefc66c8eebfe273f
  Building wheel for runfolder (setup.py): started
  Building wheel for runfolder (setup.py): finished with status 'done'
  Created wheel for runfolder: filename=runfolder-1.5.0-py2-none-any.whl size=16394 sha256=66a2cc239de1bd29c54e1cbac47eaead58d09e12b224a4138332d3b3563141f8
  Stored in directory: /root/.cache/pip/wheels/9e/e5/08/12924f5a8ff3e6ef86dbfe197a64543ab86686331a5472435e
  Building wheel for backports.ssl-match-hostname (setup.py): started
  Building wheel for backports.ssl-match-hostname (setup.py): finished with status 'done'
  Created wheel for backports.ssl-match-hostname: filename=backports.ssl_match_hostname-3.7.0.1-py2.py3-none-any.whl size=6738 sha256=1c947e0f2f35d7e556dc2c462e6c465b6c251648c2dfde42b722092851a1c294
  Stored in directory: /root/.cache/pip/wheels/ce/c0/c7/557fbc2383eb37d8a281a7e58b23eb93f4cc70cd403d1d19e2
  Building wheel for watchdog (setup.py): started
  Building wheel for watchdog (setup.py): finished with status 'done'
  Created wheel for watchdog: filename=watchdog-0.10.7-py2-none-any.whl size=76125 sha256=eda4a44c54519da4a62fcfecee99bb4b4959c56afba86cfe0ce24343e27ea1ac
  Stored in directory: /root/.cache/pip/wheels/c1/ba/5c/7e1f604d6bfc0975cb4235c6e51a8708771bcd55a285dc1757
  Building wheel for pathtools (setup.py): started
  Building wheel for pathtools (setup.py): finished with status 'done'
  Created wheel for pathtools: filename=pathtools-0.1.2-py2-none-any.whl size=8784 sha256=5069d016bc22728932e0a4d899dd0de6ac4a50f2631b23ea83fee04ce548f23c
  Stored in directory: /root/.cache/pip/wheels/da/24/4e/5b716376944d90d1406666897dbd020764405d5242afb5b236
Successfully built jsonpickle tornado PyYAML nose-watch runfolder backports.ssl-match-hostname watchdog pathtools
Installing collected packages: backports.ssl-match-hostname, certifi, tornado, idna, chardet, urllib3, requests, PyYAML, arteria, jsonpickle, xmltodict, nose, pathtools, watchdog, nose-watch, pbr, funcsigs, mock, runfolder
Successfully installed PyYAML-3.13 arteria-1.1.2 backports.ssl-match-hostname-3.7.0.1 certifi-2021.10.8 chardet-3.0.4 funcsigs-1.0.2 idna-2.7 jsonpickle-0.9.2 mock-1.3.0 nose-1.3.7 nose-watch-0.9.1 pathtools-0.1.2 pbr-5.11.0 requests-2.20.0 runfolder-1.5.0 tornado-4.2.1 urllib3-1.24.3 watchdog-0.10.7 xmltodict-0.11.0
WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Removing intermediate container d6db8f4ada21
 ---> 26d683ba1c7f
Step 7/8 : EXPOSE 80
 ---> Running in 018a18309394
Removing intermediate container 018a18309394
 ---> 943b7d857f97
Step 8/8 : CMD runfolder-ws --debug --port 80 --config config/
 ---> Running in bdb5dd6a765e
Removing intermediate container bdb5dd6a765e
 ---> 0e0c274ee2d9
Successfully built 0e0c274ee2d9
Successfully tagged arteria-packs_runfolder-service:latest
WARNING: Image for service runfolder-service was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building bcl2fastq-service
Sending build context to Docker daemon  4.096kB
Step 1/15 : From centos:7
 ---> eeb6ee3f44bd
Step 2/15 : workdir /tmp
 ---> Using cache
 ---> 6fd153fedf4f
Step 3/15 : RUN yum install -y epel-release
 ---> Using cache
 ---> 6dab93cb231f
Step 4/15 : RUN yum update -y
 ---> Using cache
 ---> 3e55e1720cd3
Step 5/15 : RUN yum install -y unzip python-pip python-virtualenv git gcc-c++ wget
 ---> Using cache
 ---> 61ca51e453a3
Step 6/15 : RUN wget https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip
 ---> Running in 085da66dcef2
--2022-10-28 07:03:19--  https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip
Resolving support.illumina.com (support.illumina.com)... 63.34.87.137, 54.228.50.221, 52.210.124.118
Connecting to support.illumina.com (support.illumina.com)|63.34.87.137|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-10-28 07:03:20 ERROR 404: Not Found.

The command '/bin/sh -c wget https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-linux-x86-64.zip' returned a non-zero code: 8
ERROR: Service 'bcl2fastq-service' failed to build : Build failed
make: *** [Makefile:17: up] Error 1
```

**Comment by matrulda** [comment]
Hi @fwa93, thanks for reporting and sorry for the late response!
Yeah, unfortunately one has to log in to Illumina's website to get bcl2fastq nowadays. We should make adjustments for that. 

Like you said there are other issues as well. I got the `make up` command to work with changes made to this branch: https://github.com/matrulda/arteria-packs/tree/issue_96

But, when trying to create a virtual env for the pack it fails:
```
$ docker exec stackstorm st2 run packs.setup_virtualenv packs=arteria
.
id: 636bbaa94726fc01194119d6
status: failed
parameters: 
  packs:
  - arteria
result: 
  exit_code: 1
  result: None
  stderr: "st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "arteria" (/opt/stackstorm/packs/arteria)
st2.actions.python.SetupVirtualEnvironmentAction: INFO     Virtualenv path "/opt/stackstorm/virtualenvs/arteria" doesn't exist
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "arteria" in "/opt/stackstorm/virtualenvs/arteria"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/arteria" using Python binary "/opt/stackstorm/st2/bin/python"
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy --no-download /opt/stackstorm/virtualenvs/arteria" to create virtualenv.
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing requirement six>=1.9.0,<2.0 with command /opt/stackstorm/virtualenvs/arteria/bin/pip install six>=1.9.0,<2.0.
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 325, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 184, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 89, in run
    no_download=no_download)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 102, in setup_pack_virtualenv
    proxy_config=proxy_config, logger=logger)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 304, in install_requirement
    (requirement, stdout))
Exception: Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>=1.9.0

"
  stdout: ''

```

When repeating the command inside the container I get a little more information: 

```
$ docker exec -it stackstorm bash
root@6495d3579aaf:/# /opt/stackstorm/virtualenvs/arteria/bin/pip install six
Collecting six
/opt/stackstorm/virtualenvs/arteria/lib/python2.7/site-packagesNP&SEQ/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/stackstorm/virtualenvs/arteria/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarningtps://github.com/StackStorm/st2-docker/blob/master/docker-compose.yml
  Could not find a version that satisfies the requirement six (from versions: )
No matching distribution found for six
/opt/stackstorm/virtualenvs/arteria/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Certificate did not match expected hostname: pypi.org. Certificate: {'notAfter': 'Aug 27 18:45:09 2023 GMT', 'subjectAltName': (('DNS', 'www.python.org'), ('DNS', '*.python.org'), ('DNS', 'docs.python.org'), ('DNS', 'downloads.python.org'), ('DNS', 'pypi.python.org')), 'subject': ((('commonName', u'www.python.org'),),)}

```

I am not sure, but I think this could be related to the py2 version bundled with this version of Stackstorm (pip + certificates being too old and py2 being generally dead). I think it's worth trying a newer version. However, Stackstorm do no longer maintain the single docker image solution, the latest version for that image is 3.1.0 and I get a smiliar error when trying that one (which also is bundled with py2.7). Trying a later version than that would require a lot of changes, implementing the new model where stackstorm services are run in individual containers: see https://github.com/StackStorm/st2-docker/blob/v3.7.0/docker-compose.yml. I'm not sure I will have the time to look into that in the near future I'm afraid, but dumping this information here if someone wants to give it a shot. 

Worth noting as well, when using a Stackstorm version > 3.2.0, the workflows have to be ported from mistral to orquesta. This tool can be used to do that: https://github.com/StackStorm/orquestaconvert (or @Aratz 's version that is more compatible with the way our facility defined mistral workflows: https://github.com/Aratz/orquestaconvert)

**Comment by matrulda** [comment]
@fwa93 Please try the latest version of the master branch. @Smeds converted the workflows and took care of the issues mentioned in this post! :tada:

**Comment by fwa93** [comment]
Thank you so much for your replies and the update which worked great!  /Frans
